FROM debian
RUN apt-get update && apt-get install -y \
  curl \
  python3.7 \
  jq \
  unzip && \
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
  -o "awscliv2.zip" && \
  unzip awscliv2.zip && \
  rm awscliv2.zip && \
  ./aws/install && \ 
  apt-get upgrade -y && \
  rm -r /var/lib/apt/lists /var/cache/apt/archives
CMD [ "bash" ]